{
 "title": "Quarkus Registry",
 "description": "Dashboard for the Quarkus Registry service",
 "tags": [ "quarkus" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "route",
    "query": {
     "query": "label_values(haproxy_backend_http_responses_total, route)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_backend_http_responses_total{route=\"$route\",code=\"5xx\"}[$__range]))\n/\nsum(increase(haproxy_backend_http_responses_total{route=\"$route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{route=\"$route\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{route=\"$route\",code=\"5xx\"}[5m])) /\nsum(rate(haproxy_backend_http_responses_total{route=\"$route\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Alert list",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 1 },
   "targets": [
    {}
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"quarkus-registry-app\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage vs limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=~\"quarkus-registry-app\"}) by (container) /\nsum(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container=~\"quarkus-registry-app\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"quarkus-registry-app\"}[5m])) by (container)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Path latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "/maven/{path:.+} latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",uri=\"/maven/{path:.+}\",code!~\"5xx\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",uri=\"/maven/{path:.+}\",code!~\"5xx\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_requests_seconds_bucket{namespace=\"$namespace\",uri=\"/maven/{path:.+}\",code!~\"5xx\"}[5m])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}