create table platform_release_category
(
    id bigint generated by default as identity
        constraint platform_release_category_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    metadata json,
    platform_release_id bigint not null
        constraint platform_release_fkey
            references platform_release,
    category_id bigint not null
        constraint category_fkey
            references category,
    constraint platform_release_category_nkey
        unique (platform_release_id, category_id)
);