create table category
(
    id bigint generated by default as identity
        constraint category_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    description varchar,
    metadata json,
    name varchar not null
        constraint category_nkey
            unique
);

create table extension
(
    id bigint generated by default as identity
        constraint extension_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    artifact_id varchar not null,
    description varchar,
    group_id varchar not null,
    name varchar not null,
    constraint extension_nkey
        unique (artifact_id, group_id)
);

create table extension_release
(
    id bigint generated by default as identity
        constraint extension_release_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    quarkus_core varchar not null,
    metadata json,
    version varchar not null,
    version_sortable varchar not null,
    extension_id bigint not null
        constraint fka1ko47ipb9gxqh6jhwy704b7
            references extension,
    constraint extension_release_nkey
        unique (extension_id, version)
);

create table extension_release_compatible
(
    id bigint generated by default as identity
        constraint extension_release_compatible_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    quarkus_core varchar,
    extension_release_id bigint not null
        constraint extension_release_compatible_fkey
            references extension_release,
    constraint extension_release_compatible_nkey
        unique (extension_release_id, quarkus_core)
);

create table platform
(
    id bigint generated by default as identity
        constraint platform_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    artifact_id varchar not null,
    group_id varchar not null,
    is_default boolean default false,
    constraint platform_nkey
        unique (artifact_id, group_id)
);

create table platform_release
(
    id bigint generated by default as identity
        constraint platform_release_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    metadata json,
    version varchar not null,
    version_sortable varchar not null,
    quarkus_core varchar not null,
    quarkus_core_upstream varchar,
    platform_id bigint
        constraint platform_fkey
            references platform,
    constraint platform_release_nkey
        unique (platform_id, version)
);

create table platform_extension
(
    id bigint generated by default as identity
        constraint platform_extension_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    metadata json,
    extension_release_id bigint not null
        constraint platform_extension_release_fkey
            references extension_release,
    platform_release_id bigint not null
        constraint platform_platform_release_fkey
            references platform_release,
    constraint platform_extension_nkey
        unique (extension_release_id, platform_release_id)
);

create table platform_release_category
(
    id bigint generated by default as identity
        constraint platform_release_category_pkey
            primary key,
    created_at timestamptz default CURRENT_TIMESTAMP,
    description varchar,
    metadata json,
    name varchar,
    category_id bigint not null
        constraint platform_release_category_category_fkey
            references category,
    platform_release_id bigint not null
        constraint platform_release_category_fkey
            references platform_release,
    constraint platform_release_category_nkey
        unique (category_id, platform_release_id)
);