INSERT INTO category (name, description) VALUES ('Core', 'Essential Quarkus components. Provided automatically');
INSERT INTO category (name, description) VALUES ('Web', 'Everything you need for REST endpoints, HTTP and web formats like JSON');
INSERT INTO category (name, description) VALUES ('Data', 'Accessing and managing your data (RDBMS, NoSQL, caching, transaction management, etc)');
INSERT INTO category (name, description) VALUES ('Messaging', 'Send and receives message to various messaging systems (AMQP, Kafka etc)');
INSERT INTO category (name, description) VALUES ('Reactive', 'Non blocking stack and connectors');
INSERT INTO category (name, description) VALUES ('Cloud', 'Useful for Cloud Native deployments platforms like Kubernetes and cloud providers');
INSERT INTO category (name, description) VALUES ('Observability', 'Metrics, tracing, etc');
INSERT INTO category (name, description) VALUES ('Security', 'Everything you need to secure your application');
INSERT INTO category (name, description) VALUES ('Integration', 'Connectors to read to write from a skew of systems (file, S#, Twitter, etc)');
INSERT INTO category (name, description) VALUES ('gRPC', 'gRPC integration');
INSERT INTO category (name, description) VALUES ('Business Automation', 'Rules engine, BPM, etc');
INSERT INTO category (name, description) VALUES ('Serialization', 'Serializing and deserializing various formats');
INSERT INTO category (name, description) VALUES ('Miscellaneous', 'Mixed bag of good stuff');
INSERT INTO category (name, description) VALUES ('Compatibility', 'Support for alternative programming models on Quarkus');
INSERT INTO category (name, description) VALUES ('Alternative languages', 'Support for other JVM based languages');
