create table extension_release_compatible
(
    id bigint generated by default as identity
        constraint extension_release_compatible_pkey
            primary key,
    created_at timestamp default CURRENT_TIMESTAMP,
    quarkus_core varchar(255),
    extension_release_id bigint not null
        constraint extension_release_compatible_fkey
            references extension_release,
    constraint extension_release_compatible_nkey
        unique (extension_release_id, quarkus_core)
);
