@startuml
'https://plantuml.com/deployment-diagram

[Quarkus Registry] as app

database db [
  PostgreSQL
]

() Maven - app
app -> db

note top of Maven: Data is exposed in a Maven 2 Repository layout

@enduml