@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Quarkus Tooling" as qtu
boundary "Maven Endpoint" as maven

qtu -> maven: Request Registry configuration
maven --> qtu: Return Registry JSON

@enduml